//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIUBStudent
    {
        public AIUBStudent()
        {
            this.CourseStudentRegistrations = new HashSet<CourseStudentRegistration>();
            this.Registrations = new HashSet<Registration>();
        }
    
        public int Id { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<CourseStudentRegistration> CourseStudentRegistrations { get; set; }
        public virtual ICollection<Registration> Registrations { get; set; }
    }
}
