//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIUB_Course
    {
        public AIUB_Course()
        {
            this.CourseStudentRegistrations = new HashSet<CourseStudentRegistration>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Credit { get; set; }
        public int Capacity { get; set; }
        public string Type { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<CourseStudentRegistration> CourseStudentRegistrations { get; set; }
    }
}
