//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseStudentRegistration
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int CourseId { get; set; }
        public int RegistrationId { get; set; }
    
        public virtual AIUB_Course AIUB_Course { get; set; }
        public virtual AIUBStudent AIUBStudent { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
