//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.AIUB_Course = new HashSet<AIUB_Course>();
            this.AIUBStudents = new HashSet<AIUBStudent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<AIUB_Course> AIUB_Course { get; set; }
        public virtual ICollection<AIUBStudent> AIUBStudents { get; set; }
    }
}
