//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystem.DB_Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public Registration()
        {
            this.CourseStudentRegistrations = new HashSet<CourseStudentRegistration>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public int StudentId { get; set; }
    
        public virtual AIUBStudent AIUBStudent { get; set; }
        public virtual ICollection<CourseStudentRegistration> CourseStudentRegistrations { get; set; }
    }
}
